# Generated by Django 5.1.1 on 2024-09-19 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=50),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.category')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyHolderPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], max_length=50)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.policy')),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.policyholder')),
            ],
        ),
        migrations.AddField(
            model_name='policyholder',
            name='policies',
            field=models.ManyToManyField(through='insurance.PolicyHolderPolicy', to='insurance.policy'),
        ),
    ]
