# Generated by Django 5.1.1 on 2024-09-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_customuser_role_policy_policyholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholderpolicy',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
